var API_REVANSTORE = '/api/revanstore';
var API_RVNSTORE = '/api/rvnstore';
var WHATSAPP_NUMBER = "6289520418604";
var MAX_TOPUP_AMOUNT = 2147483647;
var AUTO_DELETE_DAYS = 3;
var MAX_PASSWORD_LENGTH = 20;

var currentUser = null;
var currentAccount = null;
var currentAuthToken = null;
var pendingAction = null;
var pendingData = null;
var lastDeviceId = null;

async function callRevanstore(path, method, data) {
    var res = await fetch(API_REVANSTORE, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ path: path, method: method || 'GET', data: data || null }) });
    var text = await res.text(); if (!text || text === 'null') return null;
    return JSON.parse(text);
}

async function callRvnstore(endpoint, method, body, authToken) {
    var res = await fetch(API_RVNSTORE, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ endpoint: endpoint, method: method || 'POST', body: body || null, authToken: authToken || null }) });
    return await res.json();
}

function showAlert(message, type, duration) { type = type || 'info'; duration = duration || 3000; var d = document.getElementById('alert'); var icons = { success: 'fa-check-circle', error: 'fa-exclamation-circle', warning: 'fa-exclamation-triangle', info: 'fa-info-circle' }; d.innerHTML = '<div class="alert-content"><i class="fas ' + (icons[type] || 'fa-info-circle') + '"></i><span>' + message + '</span></div>'; d.className = 'alert ' + type + ' show'; setTimeout(function() { d.classList.remove('show'); }, duration); }
function formatCurrency(a) { if (!a && a !== 0) return 'Rp 0'; return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0, maximumFractionDigits: 0 }).format(Math.abs(a)); }

function parseAmount(input) { if (!input || input.trim() === '') return 0; var c = input.toUpperCase().replace(/\s/g, ''); if (c === '2M' || c === '2 M') return MAX_TOPUP_AMOUNT; var m = 1, ci = c; if (c.includes('M') && !c.includes('JT') && !c.includes('MAX')) { m = 1000000000; ci = c.replace('M', ''); } else if (c.includes('JT')) { m = 1000000; ci = c.replace('JT', ''); } else if (c.includes('RB') || c.includes('K')) { m = 1000; ci = c.replace(/[KRB]/g, ''); } else if (c.includes('MAX')) return MAX_TOPUP_AMOUNT; var n = parseFloat(ci.replace(/\./g, '').replace(',', '.')); var r = isNaN(n) ? 0 : Math.round(n * m); return Math.min(r, MAX_TOPUP_AMOUNT); }

function validateTopupAmount() { var i = document.getElementById('topupAmount'), p = document.getElementById('amountPreview'), pv = document.getElementById('amountPreviewValue'); var a = parseAmount(i.value); if (a > 0 && i.value.trim() !== '') { p.style.display = 'block'; pv.textContent = formatCurrency(a); if (i.value.toUpperCase().trim() === '2M') { pv.innerHTML = formatCurrency(a) + ' <span class="max-text">(Maksimal BUSSID)</span>'; pv.className = 'value max-amount'; i.classList.add('input-success'); } else if (a > MAX_TOPUP_AMOUNT) { i.classList.add('input-error'); pv.className = 'value exceeded-amount'; pv.innerHTML = formatCurrency(a) + ' <span class="exceeded-text">(Melebihi batas maksimal)</span>'; } else if (a === MAX_TOPUP_AMOUNT) { i.classList.add('input-success'); pv.className = 'value max-amount'; pv.innerHTML = formatCurrency(a) + ' <span class="max-text">(Maksimal BUSSID)</span>'; } else { i.classList.remove('input-error', 'input-success'); pv.className = 'value normal-amount'; } } else { p.style.display = 'none'; i.classList.remove('input-error', 'input-success'); } }

function hideAllSections() { var s = ['accountInfo', 'topupSection', 'kurasSection', 'historySection', 'settingsSection', 'receiptSection']; s.forEach(function(id) { var e = document.getElementById(id); if (e) e.style.display = 'none'; }); var sc = document.querySelector('.search-card'); if (sc) sc.style.display = 'none'; }
function showHome() { hideAllSections(); document.querySelector('.search-card').style.display = 'block'; document.getElementById('accountInfo').style.display = 'none'; document.getElementById('topupSection').style.display = 'none'; document.getElementById('kurasSection').style.display = 'none'; var t = document.getElementById('trxLagiModal'); if (t) t.style.display = 'none'; }

function parseDate(d) { if (!d) return null; var p = d.split('/'); if (p.length !== 3) return null; var m = parseInt(p[0]) - 1, day = parseInt(p[1]), y = parseInt(p[2]); if (isNaN(day) || isNaN(m) || isNaN(y)) return null; if (m < 0 || m > 11) return null; if (day < 1 || day > 31) return null; var dt = new Date(y, m, day); if (dt.getMonth() !== m || dt.getDate() !== day) return null; return dt; }
function formatDate(d) { if (!d) return ''; return String(d.getMonth() + 1).padStart(2, '0') + '/' + String(d.getDate()).padStart(2, '0') + '/' + d.getFullYear(); }
function calcDays(exp) { if (!exp) return -999; if (exp.includes('9999')) return 999999; var e = parseDate(exp); if (!e) return -999; var n = new Date(); n.setHours(0, 0, 0, 0); return Math.ceil((e - n) / 86400000); }
function getExpiryColorClass(d) { if (d === 999999) return 'masa-aktif-hijau'; if (d > 3) return 'masa-aktif-hijau'; if (d >= 1 && d <= 3) return 'masa-aktif-kuning'; return 'masa-aktif-merah'; }
function getDaysLeftText(d) { if (d === 999999) return '♾️ Permanent'; if (d < 0) return '⏰ Telah habis (' + Math.abs(d) + ' hari)'; if (d === 0) return '⚠️ Berakhir hari ini'; if (d === 1) return '📅 sisa 1 hari'; return '📅 sisa ' + d + ' hari'; }
function getDaysLeftClass(d) { if (d === 999999) return 'days-permanent'; if (d <= 0) return 'days-red'; if (d <= 3) return 'days-yellow'; return 'days-green'; }
function checkAccountExpiry(u) { var d = calcDays(u.expiry_date); return { expired: d <= 0 && d !== 999999, daysLeft: d, expiryDate: u.expiry_date, colorClass: getExpiryColorClass(d), daysLeftText: getDaysLeftText(d), daysLeftClass: getDaysLeftClass(d) }; }

function showExpiredBanner() { document.getElementById('expiredBanner').style.display = 'flex'; document.getElementById('mainApp').style.display = 'none'; document.getElementById('loginScreen').style.display = 'none'; showAlert('Masa aktif akun telah habis!', 'error'); }
function closeExpiredBanner() { document.getElementById('expiredBanner').style.display = 'none'; logout(); }
function openWhatsApp() { window.open('https://wa.me/' + WHATSAPP_NUMBER + '?text=' + encodeURIComponent('Halo admin'), '_blank'); }
function updatePasswordCounter(f) { var i = document.getElementById(f), c = document.getElementById(f + 'CharCount'); if (i && c) c.textContent = i.value.length + '/' + MAX_PASSWORD_LENGTH; }

async function autoDeleteOldTransactions() { try { var t = Date.now() - (AUTO_DELETE_DAYS * 86400000); var data = await callRevanstore('transactions', 'GET'); if (data && typeof data === 'object') { for (var k in data) { if (data[k].timestamp < t) { await callRevanstore('transactions/' + k, 'DELETE'); } } } } catch (e) {} }

function showDeleteHistoryConfirm() { document.getElementById('deleteHistoryModal').classList.add('active'); }
function closeDeleteHistoryModal() { document.getElementById('deleteHistoryModal').classList.remove('active'); }

async function deleteAllHistory() {
    try { showAlert('Menghapus...', 'info'); var data = await callRevanstore('transactions', 'GET'); if (!data || typeof data !== 'object') { showAlert('Tidak ada riwayat!', 'warning'); closeDeleteHistoryModal(); return; } var c = 0; for (var k in data) { if (data[k].operator === currentUser.username) { await callRevanstore('transactions/' + k, 'DELETE'); c++; } } closeDeleteHistoryModal(); showAlert('Berhasil menghapus ' + c + ' riwayat!', 'success'); } catch (e) { showAlert('Gagal!', 'error'); closeDeleteHistoryModal(); }
}

async function login() {
    var u = document.getElementById('username').value.trim(), p = document.getElementById('password').value.trim();
    if (!u || !p) { showAlert('Isi username dan password!', 'error'); return; }
    showAlert('Sedang login...', 'info');
    try { var users = await callRevanstore('users', 'GET'); if (!users || typeof users !== 'object') { showAlert('Gagal!', 'error'); return; } var uk = null, ur = null; for (var k in users) { if (users[k].username === u && users[k].password === p) { uk = k; ur = users[k]; break; } } if (!ur) { showAlert('Username atau password salah!', 'error'); return; } var ec = checkAccountExpiry(ur); if (ec.expired) { showExpiredBanner(); return; } await callRevanstore('users/' + uk, 'PATCH', { last_login: Date.now() }); currentUser = { id: uk, username: ur.username, password: ur.password, role: ur.role || 'Operator', full_name: ur.full_name || ur.username, expiry_date: ur.expiry_date || '', last_login: Date.now() }; document.getElementById('loginScreen').style.display = 'none'; document.getElementById('mainApp').style.display = 'block'; showHome(); showAlert('Login berhasil!', 'success'); updateProfileInfo(); localStorage.setItem('bussid_session', JSON.stringify({ username: u, password: p, user_id: uk, timestamp: Date.now() })); } catch (e) { showAlert('Login gagal!', 'error'); }
}

function updateProfileInfo() { if (!currentUser) return; var ec = checkAccountExpiry(currentUser); document.getElementById('profileUsername').textContent = currentUser.username; document.getElementById('profileName').textContent = currentUser.full_name || currentUser.username; document.getElementById('profileRole').textContent = currentUser.role || 'Operator'; document.getElementById('profileRole').className = 'profile-value role-biru'; document.getElementById('profileExpiry').innerHTML = (currentUser.expiry_date || 'Tidak ada') + ' <span class="expiry-days-left ' + ec.daysLeftClass + '">' + ec.daysLeftText + '</span>'; document.getElementById('profileExpiry').className = 'profile-value ' + ec.colorClass; if (currentUser.last_login) document.getElementById('profileLastLogin').textContent = new Date(currentUser.last_login).toLocaleString('id-ID'); else document.getElementById('profileLastLogin').textContent = 'Belum pernah'; }

function logout() { currentUser = null; currentAccount = null; currentAuthToken = null; document.getElementById('mainApp').style.display = 'none'; document.getElementById('expiredBanner').style.display = 'none'; document.getElementById('loginScreen').style.display = 'block'; document.getElementById('username').value = ''; document.getElementById('password').value = ''; localStorage.removeItem('bussid_session'); showAlert('Logout berhasil!', 'success'); }

async function searchAccount() { var d = document.getElementById('deviceId').value.trim(); if (!d) { showAlert('Masukkan Device ID!', 'error'); return; } var ok = await loginWithDeviceId(d); if (ok) { lastDeviceId = d; showAccountInfo(currentAccount); hideAllSections(); document.getElementById('accountInfo').style.display = 'block'; showAlert('Akun ditemukan!', 'success'); } }

async function loginWithDeviceId(d) { showAlert('Login BUSSID...', 'info'); try { var ci = d.trim(); if (ci.includes('.')) { currentAuthToken = ci; var ui = await getUserInfoFromPlayFab(); if (ui) { currentAccount = { deviceId: ci, name: ui.name, balance: ui.balance, facebook: ui.facebook, facebookAvatarUrl: ui.facebookAvatarUrl, playFabId: ui.playFabId }; return true; } } else { var cd = ci.toLowerCase().replace(/^android-/, ''); var ld = { TitleId: "4AE9", AndroidDeviceId: cd, CreateAccount: true, InfoRequestParameters: { GetUserAccountInfo: true, GetUserVirtualCurrency: true, GetPlayerProfile: true } }; var data = await callRvnstore('/Client/LoginWithAndroidDeviceID', 'POST', ld, null); if (data.data && data.data.SessionTicket) { currentAuthToken = data.data.SessionTicket; var ui = await getUserInfoFromPlayFab(); if (ui) { currentAccount = { deviceId: cd, name: ui.name, balance: ui.balance, facebook: ui.facebook, facebookAvatarUrl: ui.facebookAvatarUrl, playFabId: ui.playFabId }; return true; } } } throw new Error('Gagal'); } catch (e) { showAlert('Gagal: ' + e.message, 'error'); return false; } }

async function getUserInfoFromPlayFab() { if (!currentAuthToken) return null; try { var d = { InfoRequestParameters: { GetUserAccountInfo: true, GetUserVirtualCurrency: true, GetPlayerProfile: true } }; var r = await callRvnstore('/Client/GetPlayerCombinedInfo', 'POST', d, currentAuthToken); if (r.data) { var i = r.data.InfoResultPayload; var a = i.AccountInfo; var fb = { id: null, name: 'Tidak tertaut', email: null, isConnected: false }; var fav = null; if (a && a.FacebookInfo) { var fi = a.FacebookInfo; fb = { id: fi.FacebookId || null, name: fi.FullName || 'Tidak tertaut', email: fi.Email || null, isConnected: true }; if (fb.id) fav = 'https://graph.facebook.com/' + fb.id + '/picture?type=large'; } return { name: (a && a.TitleInfo) ? (a.TitleInfo.DisplayName || 'Unknown') : 'Unknown', balance: i.UserVirtualCurrency ? (i.UserVirtualCurrency.RP || 0) : 0, facebook: fb, facebookAvatarUrl: fav, playFabId: a ? (a.PlayFabId || '-') : '-' }; } } catch (e) {} return null; }

function tampilkanFotoProfile(ai) { var fc = document.getElementById('profilePhoto'); if (!fc) return; fc.innerHTML = ''; var av = ai && ai.facebookAvatarUrl ? ai.facebookAvatarUrl : null; if (av && av !== 'null' && av !== '') { var img = document.createElement('img'); img.src = av; img.style.width = '100%'; img.style.height = '100%'; img.style.objectFit = 'cover'; img.style.borderRadius = '50%'; img.onerror = function() { fc.innerHTML = '<i class="fas fa-user"></i>'; }; fc.appendChild(img); } else { fc.innerHTML = '<i class="fas fa-user"></i>'; } }

function tampilkanInfoFacebook(fb) { var fd = document.getElementById('facebookDetails'); if (!fd) return; if (fb && fb.isConnected && fb.id) { fd.innerHTML = '<div class="fb-info-row"><span class="fb-info-label"><i class="fab fa-facebook"></i> Status:</span><span class="fb-info-value" style="color:#1877F2;">✅ TERHUBUNG</span></div><div class="fb-info-row"><span class="fb-info-label"><i class="fab fa-facebook"></i> ID:</span><span class="fb-info-value" style="font-family:monospace;font-size:12px;">' + fb.id + '</span></div><div class="fb-info-row"><span class="fb-info-label"><i class="fas fa-user"></i> Nama:</span><span class="fb-info-value">' + (fb.name || '-') + '</span></div>'; } else { fd.innerHTML = '<div class="fb-info-row"><span class="fb-info-label"><i class="fab fa-facebook"></i> Status:</span><span class="fb-info-value" style="color:#ffaa00;">⚠️ TIDAK TERHUBUNG</span></div>'; } }

function showAccountInfo(ai) { document.getElementById('accountName').textContent = ai.name || '-'; document.getElementById('accountBalance').textContent = formatCurrency(ai.balance); document.getElementById('playfabId').textContent = ai.playFabId || '-'; tampilkanFotoProfile(ai); tampilkanInfoFacebook(ai.facebook); }
function refreshAccountInfo() { if (!currentAccount) return; showAlert('Refresh...', 'info'); setTimeout(async function() { var ni = await getUserInfoFromPlayFab(); if (ni) { currentAccount.balance = ni.balance; currentAccount.name = ni.name; currentAccount.facebook = ni.facebook; currentAccount.facebookAvatarUrl = ni.facebookAvatarUrl; currentAccount.playFabId = ni.playFabId; showAccountInfo(currentAccount); showAlert('Diperbarui!', 'success'); } }, 1000); }
function setAmount(v) { var i = document.getElementById('topupAmount'); if (i) { i.value = v; validateTopupAmount(); } }
function showTopupFromAccount() { if (!currentAccount) return; document.getElementById('topupAccountName').textContent = currentAccount.name; document.getElementById('topupCurrentBalance').textContent = formatCurrency(currentAccount.balance); hideAllSections(); document.getElementById('topupSection').style.display = 'block'; }
function showKurasFromAccount() { if (!currentAccount) return; document.getElementById('kurasAccountName').textContent = currentAccount.name; document.getElementById('kurasCurrentBalance').textContent = formatCurrency(currentAccount.balance); hideAllSections(); document.getElementById('kurasSection').style.display = 'block'; }

function processTopup() { if (!currentAccount) return; var a = parseAmount(document.getElementById('topupAmount').value); if (a <= 0) { showAlert('Jumlah!', 'error'); return; } showConfirm('TOP UP', 'Top up ' + formatCurrency(a) + '?', 'topup', { amount: a }); }
function processKuras() { if (!currentAccount) return; var i = document.getElementById('kurasAmount').value.trim(); var a = i ? parseAmount(i) : currentAccount.balance; if (a <= 0) { showAlert('Saldo!', 'error'); return; } showConfirm('KURAS', 'Kuras ' + formatCurrency(a) + '?', 'kuras', { amount: a }); }

async function addCash(a) { if (!currentAuthToken) return false; var r = await callRvnstore('/Client/ExecuteCloudScript', 'POST', { FunctionName: "AddRp", FunctionParameter: { addValue: a }, RevisionSelection: "Live", GeneratePlayStreamEvent: true }, currentAuthToken); if (r.data) { await new Promise(function(res) { setTimeout(res, 2000); }); var ni = await getUserInfoFromPlayFab(); if (ni) { currentAccount.balance = ni.balance; currentAccount.facebook = ni.facebook; currentAccount.facebookAvatarUrl = ni.facebookAvatarUrl; currentAccount.playFabId = ni.playFabId; showAccountInfo(currentAccount); return true; } } return false; }

async function executeTopup(a) { showAlert('Proses...', 'info'); var ob = currentAccount.balance; if (await addCash(a)) { var t = { type: 'topup', deviceId: currentAccount.deviceId, accountName: currentAccount.name, amount: a, oldBalance: ob, newBalance: currentAccount.balance, operator: currentUser.username, timestamp: Date.now(), status: 'success' }; await callRevanstore('transactions', 'POST', t); showReceipt(t); showAlert('Berhasil!', 'success'); } else showAlert('Gagal!', 'error'); }
async function executeKuras(a) { showAlert('Proses...', 'info'); var ob = currentAccount.balance; if (await addCash(-a)) { var t = { type: 'kuras', deviceId: currentAccount.deviceId, accountName: currentAccount.name, amount: a, oldBalance: ob, newBalance: currentAccount.balance, operator: currentUser.username, timestamp: Date.now(), status: 'success' }; await callRevanstore('transactions', 'POST', t); showReceipt(t); showAlert('Berhasil!', 'success'); } else showAlert('Gagal!', 'error'); }

function showReceipt(t) { hideAllSections(); var ty = t.type === 'topup' ? 'TOP UP' : 'KURAS'; var sg = t.type === 'topup' ? '+' : '-'; document.getElementById('receiptContent').innerHTML = '<div class="receipt-content"><div class="receipt-header"><h3>BUS SIMULATOR ID</h3><p>Struk</p></div><div class="receipt-details"><div class="receipt-row"><span>Akun:</span><span>' + t.accountName + '</span></div><div class="receipt-row"><span>Jenis:</span><span>' + ty + '</span></div><div class="receipt-row"><span>Jumlah:</span><span style="color:' + (t.type==='topup'?'#00cc88':'#ffaa00') + '">' + sg + formatCurrency(t.amount) + '</span></div><div class="receipt-row"><span>Sebelum:</span><span>' + formatCurrency(t.oldBalance) + '</span></div><div class="receipt-row"><span>Sesudah:</span><span>' + formatCurrency(t.newBalance) + '</span></div><div class="receipt-row"><span>Tanggal:</span><span>' + new Date(t.timestamp).toLocaleString('id-ID') + '</span></div></div></div><div style="display:flex;gap:10px;margin-top:20px;"><button class="btn btn-success" onclick="showTrxLagiModal()" style="flex:1;">TRX LAGI</button><button class="btn btn-primary" onclick="showHome()" style="flex:1;">HOME</button></div>'; document.getElementById('receiptSection').style.display = 'block'; }

function showTrxLagiModal() { document.getElementById('trxLagiModal').style.display = 'flex'; }
function tutupTrxLagiModal() { document.getElementById('trxLagiModal').style.display = 'none'; showHome(); }
function pilihTopupLagi() { tutupTrxLagiModal(); showTopupFromAccount(); }
function pilihKurasLagi() { tutupTrxLagiModal(); showKurasFromAccount(); }

async function showHistory() { hideAllSections(); document.getElementById('historySection').style.display = 'block'; try { var data = await callRevanstore('transactions', 'GET'); var ld = document.getElementById('transactionsList'); if (!data || typeof data !== 'object') { ld.innerHTML = '<p style="text-align:center;color:#666;">Belum ada</p>'; return; } var arr = Object.keys(data).map(function(k) { return { id: k, type: data[k].type, accountName: data[k].accountName, amount: data[k].amount, oldBalance: data[k].oldBalance, newBalance: data[k].newBalance, operator: data[k].operator, timestamp: data[k].timestamp }; }).filter(function(t) { return t.operator === currentUser.username; }).sort(function(a, b) { return b.timestamp - a.timestamp; }); if (arr.length === 0) { ld.innerHTML = '<p style="text-align:center;color:#666;">Belum ada</p>'; return; } var h = ''; arr.forEach(function(t) { h += '<div class="transaction-item ' + t.type + '"><div class="transaction-header"><div>' + t.accountName + '</div><div>' + (t.type==='topup'?'+':'-') + formatCurrency(t.amount) + '</div></div></div>'; }); ld.innerHTML = h; } catch (e) { showAlert('Gagal!', 'error'); } }

function showSettings() { hideAllSections(); document.getElementById('settingsSection').style.display = 'block'; updateProfileInfo(); }
function showConfirm(t, m, a, d) { document.getElementById('confirmTitle').innerHTML = t; document.getElementById('confirmMessage').innerHTML = m; pendingAction = a; pendingData = d; document.getElementById('confirmModal').classList.add('active'); }
function cancelConfirm() { pendingAction = null; pendingData = null; document.getElementById('confirmModal').classList.remove('active'); }
async function confirmAction() { if (!pendingAction || !pendingData) return; document.getElementById('confirmModal').classList.remove('active'); if (pendingAction === 'topup') await executeTopup(pendingData.amount); else await executeKuras(pendingData.amount); pendingAction = null; pendingData = null; }

async function checkNameAvailability() { var d = document.getElementById('nameAvailability'); d.innerHTML = '<div class="availability-checking">Mengecek...</div>'; d.style.display = 'block'; setTimeout(function() { d.innerHTML = '<div class="availability-success">Tersedia!</div>'; }, 1000); }

async function changeAccountNameSimple() { var n = document.getElementById('newAccountName').value.trim(); if (!n || !currentAuthToken) return; var r = await callRvnstore('/Client/UpdateUserTitleDisplayName', 'POST', { DisplayName: n }, currentAuthToken); if (r.data && r.data.DisplayName) { currentAccount.name = n; document.getElementById('accountName').textContent = n; showAlert('Nama diganti!', 'success'); } else showAlert('Gagal!', 'error'); }

function showNameChangeModal(m) { document.getElementById('nameChangeMessage').innerHTML = m; document.getElementById('nameChangeModal').classList.add('active'); }
function closeNameChangeModal() { document.getElementById('nameChangeModal').classList.remove('active'); }

function setupQuickAmounts() { var q = document.querySelector('.quick-amounts'); if (q) q.innerHTML = '<button class="btn-quick" onclick="setAmount(\'2M\')">2M</button><button class="btn-quick" onclick="setAmount(\'1M\')">1M</button><button class="btn-quick" onclick="setAmount(\'500JT\')">500JT</button><button class="btn-quick" onclick="setAmount(\'100JT\')">100JT</button>'; }
function setupEventListeners() { var u = document.getElementById('username'); if (u) u.addEventListener('keypress', function(e) { if (e.key === 'Enter') document.getElementById('password').focus(); }); var p = document.getElementById('password'); if (p) p.addEventListener('keypress', function(e) { if (e.key === 'Enter') login(); }); var t = document.getElementById('topupAmount'); if (t) t.addEventListener('keypress', function(e) { if (e.key === 'Enter') processTopup(); }); var d = document.getElementById('deviceId'); if (d) d.addEventListener('keypress', function(e) { if (e.key === 'Enter') searchAccount(); }); }

document.addEventListener('DOMContentLoaded', async function() { autoDeleteOldTransactions(); setupEventListeners(); setupQuickAmounts(); var s = localStorage.getItem('bussid_session'); if (s) { try { var ss = JSON.parse(s); if (Date.now() - (ss.timestamp || 0) < 7 * 86400000) { var users = await callRevanstore('users', 'GET'); if (users && typeof users === 'object') { for (var k in users) { if (users[k].username === ss.username && users[k].password === ss.password) { var u = users[k]; var ec = checkAccountExpiry(u); if (ec.expired) { showExpiredBanner(); return; } currentUser = { id: k, username: u.username, password: u.password, role: u.role || 'Operator', full_name: u.full_name || u.username, expiry_date: u.expiry_date || '', last_login: u.last_login || null }; document.getElementById('loginScreen').style.display = 'none'; document.getElementById('mainApp').style.display = 'block'; showHome(); updateProfileInfo(); showAlert('Selamat datang!', 'success'); break; } } } } } catch(e) { localStorage.removeItem('bussid_session'); } } setInterval(autoDeleteOldTransactions, 3600000); });

window.pilihTopupLagi = pilihTopupLagi; window.pilihKurasLagi = pilihKurasLagi; window.tutupTrxLagiModal = tutupTrxLagiModal; window.showTrxLagiModal = showTrxLagiModal; window.closeExpiredBanner = closeExpiredBanner; window.openWhatsApp = openWhatsApp; window.login = login; window.searchAccount = searchAccount; window.refreshAccountInfo = refreshAccountInfo; window.checkNameAvailability = checkNameAvailability; window.changeAccountNameSimple = changeAccountNameSimple; window.showTopupFromAccount = showTopupFromAccount; window.showKurasFromAccount = showKurasFromAccount; window.processTopup = processTopup; window.processKuras = processKuras; window.showHistory = showHistory; window.showSettings = showSettings; window.showHome = showHome; window.cancelConfirm = cancelConfirm; window.confirmAction = confirmAction; window.setAmount = setAmount; window.validateTopupAmount = validateTopupAmount; window.updatePasswordCounter = updatePasswordCounter; window.closeDeleteHistoryModal = closeDeleteHistoryModal; window.deleteAllHistory = deleteAllHistory; window.showDeleteHistoryConfirm = showDeleteHistoryConfirm; window.closeNameChangeModal = closeNameChangeModal;